import type { CollectionEntry } from "astro:content";
import postFilter from "./postFilter";
import relatedPostsData from "../generated/related-posts.json";

// Generated by scripts/related-posts.mjs; keys and values are entry ids.
const relatedMap = relatedPostsData.posts as Record<string, string[]>;

// More candidates are stored than shown so that a scheduled or re-drafted
// candidate leaves the section full instead of partially empty.
const getRelatedPosts = (
  posts: CollectionEntry<"blog">[],
  currentId: string,
  limit = 3
): CollectionEntry<"blog">[] => {
  const postsById = new Map(posts.map(post => [post.id, post]));
  const candidateIds = relatedMap[currentId] ?? [];
  return candidateIds
    .map(id => postsById.get(id))
    .filter(
      (post): post is CollectionEntry<"blog"> =>
        post !== undefined && postFilter(post)
    )
    .slice(0, limit);
};

export default getRelatedPosts;
