/**
 * Copies the installed KaTeX stylesheet and its woff2 faces into public/katex/.
 *
 * The stylesheet used to be pulled from a CDN at a version hardcoded in the
 * markup — 0.15.2, while the markup itself was generated by whatever version
 * rehype-katex resolved. Nothing tied the two together, so the CSS styling the
 * math and the code emitting it could drift apart silently. Vendoring from
 * node_modules makes package.json the single version, and `npm run katex:check`
 * fails the moment the copy falls behind an upgrade.
 *
 * Only woff2 is copied, and the `src` lists are rewritten to match. KaTeX ships
 * woff and ttf fallbacks for browsers the site already does not serve — its own
 * faces in src/styles/fonts.css are woff2-only for the same reason. Shipping
 * all three formats would be 1.1 MB instead of 296 KB for fallbacks nothing
 * asks for.
 *
 *   node scripts/vendor-katex.mjs          copy, overwriting public/katex/
 *   node scripts/vendor-katex.mjs check    exit 1 if the copy is stale
 */
import { createRequire } from "node:module";
import {
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join } from "node:path";

const require = createRequire(import.meta.url);
const katexDir = join(require.resolve("katex/package.json"), "..");
const version = JSON.parse(
  readFileSync(join(katexDir, "package.json"), "utf8")
).version;

const outDir = join(process.cwd(), "public/katex");
const mode = process.argv[2] === "check" ? "check" : "write";

/** Drop every non-woff2 entry from each `src:` list. */
function woff2Only(css) {
  return css.replace(/src:([^;}]+)/g, (whole, list) => {
    const kept = list
      .split(/,(?![^(]*\))/)
      .map(part => part.trim())
      .filter(part => part.includes(".woff2"));
    return kept.length ? `src:${kept.join(",")}` : whole;
  });
}

const css = woff2Only(readFileSync(join(katexDir, "dist/katex.min.css"), "utf8"));
const fonts = readdirSync(join(katexDir, "dist/fonts")).filter(f =>
  f.endsWith(".woff2")
);
const stamp = `${version}\n${fonts.length} woff2\n`;

if (mode === "check") {
  let current = "";
  try {
    current = readFileSync(join(outDir, "VERSION"), "utf8");
  } catch {
    /* missing counts as stale */
  }
  if (current !== stamp) {
    console.error(
      `katex: public/katex is stale (have ${JSON.stringify(current)}, ` +
        `want ${JSON.stringify(stamp)}). Run: npm run katex:vendor`
    );
    process.exit(1);
  }
  console.log(`katex: public/katex up to date (${version})`);
  process.exit(0);
}

rmSync(outDir, { recursive: true, force: true });
mkdirSync(join(outDir, "fonts"), { recursive: true });
writeFileSync(join(outDir, "katex.min.css"), css);
for (const font of fonts) {
  writeFileSync(
    join(outDir, "fonts", font),
    readFileSync(join(katexDir, "dist/fonts", font))
  );
}
writeFileSync(join(outDir, "VERSION"), stamp);
console.log(`katex: vendored ${version} (${fonts.length} woff2 faces)`);
