/**
 * Copies the installed KaTeX stylesheet and its woff2 faces into public/katex/.
 *
 * The stylesheet used to be pulled from a CDN at a version hardcoded in the
 * markup — 0.15.2, while the markup itself was generated by whatever version
 * rehype-katex resolved. Nothing tied the two together, so the CSS styling the
 * math and the code emitting it could drift apart silently. Vendoring from
 * node_modules makes package.json the single version, and `npm run katex:check`
 * fails the moment the copy falls behind an upgrade.
 *
 * Only woff2 is copied, and the `src` lists are rewritten to match. KaTeX ships
 * woff and ttf fallbacks for browsers the site already does not serve — its own
 * faces in src/styles/fonts.css are woff2-only for the same reason. Shipping
 * all three formats would be 1.1 MB instead of 296 KB for fallbacks nothing
 * asks for.
 *
 *   node scripts/vendor-katex.mjs          copy, overwriting public/katex/
 *   node scripts/vendor-katex.mjs check    exit 1 if the copy is not byte-exact
 *
 * `check` compares every file, not a version stamp: a stamp says which release
 * was vendored, not that the bytes are still there. A deleted stylesheet or a
 * truncated font would pass a stamp check and ship a post with unstyled math.
 */
import { createRequire } from "node:module";
import {
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { join, relative, sep } from "node:path";

const require = createRequire(import.meta.url);
const katexDir = join(require.resolve("katex/package.json"), "..");
const version = JSON.parse(
  readFileSync(join(katexDir, "package.json"), "utf8")
).version;

const outDir = join(process.cwd(), "public/katex");
const mode = process.argv[2] === "check" ? "check" : "write";

/** Drop every non-woff2 entry from each `src:` list. */
function woff2Only(css) {
  return css.replace(/src:([^;}]+)/g, (whole, list) => {
    const kept = list
      .split(/,(?![^(]*\))/)
      .map(part => part.trim())
      .filter(part => part.includes(".woff2"));
    return kept.length ? `src:${kept.join(",")}` : whole;
  });
}

/**
 * The exact tree public/katex should contain, as posix-style paths. Both modes
 * build this, so `check` compares against what `write` would actually produce
 * rather than against a summary of it.
 */
function buildExpected() {
  const files = new Map();
  files.set(
    "katex.min.css",
    Buffer.from(
      woff2Only(readFileSync(join(katexDir, "dist/katex.min.css"), "utf8"))
    )
  );
  const fonts = readdirSync(join(katexDir, "dist/fonts"))
    .filter(f => f.endsWith(".woff2"))
    .sort();
  for (const font of fonts) {
    files.set(
      `fonts/${font}`,
      readFileSync(join(katexDir, "dist/fonts", font))
    );
  }
  // Human-readable marker only. The check does not rely on it.
  files.set("VERSION", Buffer.from(`${version}\n${fonts.length} woff2\n`));
  return files;
}

/** Every file under dir, as posix-style paths relative to it. */
function listActual(dir) {
  const out = [];
  const walk = base => {
    let entries;
    try {
      entries = readdirSync(base, { withFileTypes: true });
    } catch {
      return; // missing directory: reported as missing files instead
    }
    for (const entry of entries) {
      const full = join(base, entry.name);
      if (entry.isDirectory()) walk(full);
      else out.push(relative(dir, full).split(sep).join("/"));
    }
  };
  walk(dir);
  return out;
}

const expected = buildExpected();

if (mode === "check") {
  const missing = [];
  const differing = [];

  for (const [name, want] of expected) {
    let have;
    try {
      have = readFileSync(join(outDir, name));
    } catch {
      missing.push(name);
      continue;
    }
    if (!have.equals(want)) differing.push(name);
  }

  const extra = listActual(outDir).filter(name => !expected.has(name));

  if (missing.length || differing.length || extra.length) {
    const say = (label, list) =>
      list.length &&
      console.error(
        `  ${label}: ${list.slice(0, 5).join(", ")}` +
          (list.length > 5 ? ` (+${list.length - 5} more)` : "")
      );
    console.error(`katex: public/katex does not match katex ${version}`);
    say("missing", missing);
    say("differs", differing);
    say("unexpected", extra);
    console.error("  Run: npm run katex:vendor");
    process.exit(1);
  }

  console.log(
    `katex: public/katex matches ${version} (${expected.size} files verified)`
  );
  process.exit(0);
}

rmSync(outDir, { recursive: true, force: true });
mkdirSync(join(outDir, "fonts"), { recursive: true });
for (const [name, contents] of expected) {
  writeFileSync(join(outDir, name), contents);
}
console.log(`katex: vendored ${version} (${expected.size} files)`);
